### ISSUE TITLE
mat file is empty

### ISSUE THREAD

**Issue by cjjjan** [ripl/nerfuser#1]
In the data prepartion process, output is scipy.io.matlab._miobase.MatReadError: Mat file appears to be empty.

what should i do?

**Comment by shengjie-lin** [comment]
Please provide details on how to reproduce the error. Specifically, what command are you calling? What data are you using?

**Comment by cjjjan** [comment]
> Please provide details on how to reproduce the error. Specifically, what command are you calling? What data are you using?
![image](https://github.com/ripl/nerfuser/assets/94848655/6dfeb129-c921-4c93-8282-e3a7be6b38c1)

data equalls yours

**Comment by cjjjan** [comment]
input command is python -m nerfuser.prep_data \
    --dataset-dir data_set \
    --vid-ids test A B C \
    --downsample 8 \
    --extract-images \
    --run-sfm \
    --write-json \
    --vis

**Comment by shengjie-lin** [comment]
It seems you are using python 3.10. During the development stage, one of the dependencies `pycolmap` only supports up to python 3.9. Can you make sure to follow the installation guide to setup the environment and try again?

**Comment by cjjjan** [comment]
Sorry, i'll try that

Thank you, reply this.

**Comment by cjjjan** [comment]
The output is same...

![image](https://github.com/ripl/nerfuser/assets/94848655/7bae0b85-83cd-4923-9cc9-c556a88b71dc)

**Comment by cjjjan** [comment]
It is my pip list

Package                  Version      Editable project location
------------------------ ------------ ----------------------------------------
absl-py                  1.4.0
addict                   2.4.0
anyio                    3.7.0
appdirs                  1.4.4
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asttokens                2.2.1
async-lru                2.0.2
attrs                    23.1.0
av                       10.0.0
Babel                    2.12.1
backcall                 0.2.0
beautifulsoup4           4.12.2
bidict                   0.22.1
bleach                   6.0.0
cachetools               5.3.1
certifi                  2023.5.7
cffi                     1.15.1
cfgv                     3.3.1
charset-normalizer       3.1.0
click                    8.1.3
comm                     0.1.3
ConfigArgParse           1.5.3
contourpy                1.1.0
cryptography             41.0.1
cycler                   0.11.0
dash                     2.10.2
dash-core-components     2.0.0
dash-html-components     2.0.0
dash-table               5.0.0
debugpy                  1.6.7
decorator                5.1.1
defusedxml               0.7.1
descartes                1.1.0
distlib                  0.3.6
docker-pycreds           0.4.0
docstring-parser         0.14.1
exceptiongroup           1.1.1
executing                1.2.0
fastjsonschema           2.17.1
filelock                 3.12.2
fire                     0.5.0
Flask                    2.2.5
fonttools                4.40.0
fqdn                     1.5.1
frozendict               2.3.8
functorch                1.13.1
gdown                    4.7.1
gitdb                    4.0.10
GitPython                3.1.31
google-auth              2.20.0
google-auth-oauthlib     1.0.0
grpcio                   1.56.0
h5py                     3.9.0
hloc                     1.3          /jaehyeon/dock/Hierarchical-Localization
identify                 2.5.24
idna                     3.4
imageio                  2.31.1
imageio-ffmpeg           0.4.8
importlib-metadata       6.7.0
importlib-resources      5.12.0
ipykernel                6.23.2
ipython                  8.14.0
ipython-genutils         0.2.0
ipywidgets               8.0.6
isoduration              20.11.0
itsdangerous             2.1.2
jaxtyping                0.2.20
jedi                     0.18.2
Jinja2                   3.1.2
joblib                   1.2.0
json5                    0.9.14
jsonpointer              2.4
jsonschema               4.17.3
jupyter                  1.0.0
jupyter_client           8.2.0
jupyter-console          6.6.3
jupyter_core             5.3.1
jupyter-events           0.6.3
jupyter-lsp              2.2.0
jupyter_server           2.6.0
jupyter_server_terminals 0.4.4
jupyterlab               4.0.2
jupyterlab-pygments      0.2.2
jupyterlab_server        2.23.0
jupyterlab-widgets       3.0.7
kiwisolver               1.4.4
kornia                   0.6.12
lazy_loader              0.2
lpips                    0.1.4
Markdown                 3.4.3
markdown-it-py           3.0.0
MarkupSafe               2.1.3
matplotlib               3.7.1
matplotlib-inline        0.1.6
mdurl                    0.1.2
mediapy                  1.1.6
mistune                  3.0.1
msgpack                  1.0.5
msgpack-numpy            0.4.8
nbclassic                1.0.0
nbclient                 0.8.0
nbconvert                7.6.0
nbformat                 5.7.0
nerfacc                  0.5.2
nerfstudio               0.3.2
nerfuser                 0.1.0
nest-asyncio             1.5.6
networkx                 3.1
ninja                    1.11.1
nodeenv                  1.8.0
notebook                 6.5.4
notebook_shim            0.2.3
numpy                    1.25.0
nuscenes-devkit          1.1.9
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
oauthlib                 3.2.2
open3d                   0.17.0
opencv-python            4.6.0.66
overrides                7.3.1
packaging                23.1
pandas                   2.0.2
pandocfilters            1.5.0
parso                    0.8.3
pathtools                0.1.2
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.5.0
pip                      23.1.2
platformdirs             3.8.0
plotly                   5.15.0
pre-commit               3.3.2
prometheus-client        0.17.0
prompt-toolkit           3.0.38
protobuf                 3.20.3
psutil                   5.9.5
ptyprocess               0.7.0
pure-eval                0.2.2
pyasn1                   0.5.0
pyasn1-modules           0.3.0
pycocotools              2.0.6
pycolmap                 0.4.0
pycparser                2.21
pyequilib                0.5.6
Pygments                 2.15.1
pyliblzfse               0.4.1
pymeshlab                2022.2.post4
pyngrok                  6.0.0
pyparsing                3.1.0
pyquaternion             0.9.9
pyrsistent               0.19.3
PySocks                  1.7.1
python-dateutil          2.8.2
python-engineio          4.4.1
python-json-logger       2.0.7
python-socketio          5.8.0
pytz                     2023.3
PyWavelets               1.4.1
PyYAML                   6.0
pyzmq                    25.1.0
qtconsole                5.4.3
QtPy                     2.3.1
requests                 2.31.0
requests-oauthlib        1.3.1
rfc3339-validator        0.1.4
rfc3986-validator        0.1.1
rich                     13.4.2
rsa                      4.9
scikit-image             0.21.0
scikit-learn             1.2.2
scipy                    1.10.1
Send2Trash               1.8.2
sentry-sdk               1.26.0
setproctitle             1.3.2
setuptools               67.8.0
shapely                  2.0.1
shtab                    1.6.2
six                      1.16.0
smmap                    5.0.0
sniffio                  1.3.0
soupsieve                2.4.1
stack-data               0.6.2
tenacity                 8.2.2
tensorboard              2.13.0
tensorboard-data-server  0.7.1
termcolor                2.3.0
terminado                0.17.1
threadpoolctl            3.1.0
tifffile                 2023.4.12
tinycss2                 1.2.1
tinycudann               1.7
tomli                    2.0.1
torch                    1.13.1
torch-fidelity           0.3.0
torchmetrics             0.11.4
torchvision              0.14.1
tornado                  6.3.2
tqdm                     4.65.0
traitlets                5.9.0
trimesh                  3.22.1
typeguard                4.0.0
typing_extensions        4.6.3
tyro                     0.5.3
tzdata                   2023.3
uri-template             1.3.0
urllib3                  1.26.16
virtualenv               20.23.1
viser                    0.0.16
wandb                    0.15.4
wcwidth                  0.2.6
webcolors                1.13
webencodings             0.5.1
websocket-client         1.6.0
websockets               11.0.3
Werkzeug                 2.2.3
wheel                    0.38.4
widgetsnbextension       4.0.7
xatlas                   0.0.7
zipp                     3.15.0



cuda is 11.7

**Comment by cjjjan** [comment]
I use  only A.mov, B.mov, C.mov and test.mov in your dataset

**Comment by shengjie-lin** [comment]
I update the installation instructions to use python 3.10 and pytorch 2. `prep_data` works fine if I setup the environment by exactly following the instructions. I am not sure that solves your issue though, as I never have that before.
It seems to me your issue is more related to missing files. Maybe `hloc` does not have writing access, and thus does not correctly save the intermediate results, which causes subsequent steps to fail.
