### ISSUE TITLE
Implement Mip-NeRF on nerfuser

### ISSUE THREAD

**Issue by Victor-Xiaoyu-Ye** [ripl/nerfuser#5]
Hi thanks for the wonderful work
 
I`m wondering is it possible to train&registrate nerfs with mipnerf/mipnef360 on the nerfuser, what file should I change to adapte it.

**Comment by shengjie-lin** [comment]
Yes, it is possible. You need to create a method `get_mipnerf_outputs()` in components.py that returns variables needed for the blending (see `get_nerfacto_outputs` for reference) and follows the mipnerf methodology (see `get_outputs` in nerfstudio's mipnerf.py). You also need to add code for loading mipnerf in view_blender.py (line 34--38). Finally, add "mipnerf" as a possible argument for `model_method` in registration.py and blending.py, and use it when calling them.
Before using nerfuser, make sure the trained mipnerf models are of reasonable quality, which may be trickier than nerfacto.

**Comment by Victor-Xiaoyu-Ye** [comment]
Thanks，I`ll get hands on it immediately.

Great response efficiency!
